### ISSUE TITLE
Add a field_custom_id to identify the field in the backend if needed

### ISSUE THREAD

**Issue by libargutxi** [collective/volto-form-block#13]
We are using volto-form-block and the default behavior works in most cases but in a few forms we need to process the form post differently. Therefore, we override the @submit-form view we have in https://github.com/collective/collective.volto.formsupport. 

 The data is something like this:

```{'block_id': '6af7d07f-214e-4d65-a86b-71ce53264ede', 'data': [{'field_id': '1629893852995', 'label': 'test field', 'value': 'test value'}], 'attachments': {}} ```

 With this information we can't identify a specific field and that is what we need. We thought to use the label but we are in a multilingual site and the label is different for each language so we need a unique value. 
I created a new branch (https://github.com/collective/volto-form-block/tree/field_custom_id) adding a "field_custom_id" new field to each field we create in the form. This way, the data we post in the form is like this:

```{'block_id': '6af7d07f-214e-4d65-a86b-71ce53264ede', 'data': [{'field_id': '1629893852995', 'label': 'test field', 'value': 'test value', 'field_custom_id': 'test_custom_id'}], 'attachments': {}} ```

 How do you see these changes? 

 Thanks in advance

**Comment by tiberiuichim** [comment]
May I suggest another pattern? Either:

- add a single "form id" field, or 
- a possibility to change the endpoint URL, so that you can register your custom endpoint.

**Comment by nzambello** [comment]
@libargutxi aren't you able to retrieve the block from the context and its id and then retrieve the field from that? You should be able if I'm not wrong. 🤔 

@cekk do you have any concerns about this? You played a lot with those ids 😅

**Comment by erral** [comment]
Not an issue anymore after https://github.com/collective/volto-form-block/pull/18
