### ISSUE TITLE
FormData actions not working in seamless mode

### ISSUE THREAD

**Issue by mbarde** [collective/volto-form-block#24]
`getFormData`, `exportCsvFormData` and `clearFormData` called from `Sidebar.jsx` call endpoints  without `++api++`, which does not work in seamless mode. Can be fixed via `flattenToAppURL`.

**Comment by tisto** [comment]
Seems like we are affected by this as well. @giuliaghisini @cekk @pnicolli is that something we can fix? @iFlameing could help here if needed.

Question: the CSV form action adapter works out of the box, right? Or is there anything an editor has to enable (like in PFG?).

cc @wolbernd

**Comment by cekk** [comment]
@tisto  i haven't looked how calls are made, but if flatten can help to solve it, probably it's a good starting point ;)
We're not using seamless mode yet in production, so this is not happened to our websites, but need to be fixed for sure.

And the "store" feature only need to be enabled in the form block settings (there should be a checkbox to enable it)

**Comment by wolbernd** [comment]
We are using 2.2.3 at the moment but I don't see any changes since then that could influence this problem. 

I did test the PR from @mbarde in a dev instance and it does solve the problem for us.

**Comment by giuliaghisini** [comment]
> We are using 2.2.3 at the moment but I don't see any changes since then that could influence this problem.
> 
> I did test the PR from @mbarde in a dev instance and it does solve the problem for us.

oh! ok i see now.. it makes sense.. i'll could make a relase

**Comment by giuliaghisini** [comment]
@mbarde @wolbernd @tisto released 2.3.3 version
