### ISSUE TITLE
`volto-subblocks` is not included as dependency

### ISSUE THREAD

**Issue by sneridagh** [collective/volto-form-block#50]

**Comment by pnicolli** [comment]
`volto-subblocks` is a peer dependency as of 3.0.0, and needs to be installed together with this add-on as mentioned in the Readme. The rationale behind this is in #45.
I understand that this probably needs to be documented better in the changelog, or at least in the github release. I will try to take some time to have a better look at conventional commits and automatic changelog stuff which has been introduced here.
