### ISSUE TITLE
Changing field type breaks form

### ISSUE THREAD

**Issue by mbarde** [collective/volto-form-block#62]
## What?

Changing field type breaks corresponding field (is not displayed anymore).

### Frontend

- plone/volto: 16.20.4
- volto-form-block: 3.0.1

### Backend

- Plone: 6.0.1
- collective.volto.formsupport: 2.7.0

## Reason

`field_type` in `formSchema.js` is an array but `FormField.jsx` expects it to be a string.

Did I miss something or can someone else confirm this?

**Comment by JeffersonBledsoe** [comment]
@mbarde Had a client file an issue this morning with this problem. I've added a PR (#64) to solve this issue

**Comment by mbarde** [comment]
Nice, thank you!
